version: '3.9'
services:
  postgres_db:
    image: postgres:15
    ports:
      - 32772:5432
    networks:
      - javaschool
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  authserver:
    image: authserver:3
    build: /Users/konstantin/IdeaProjects/Sber-cources/authorization-server/
    ports:
      - "9000:9000"
    networks:
      - javaschool
    environment:
      LIQUIBASE_ENABLED: 'true'
      DATABASE_USE: postgres
      DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/postgres
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgrespw
    depends_on:
      - postgres_db
volumes:
  db_data:
networks:
  javaschool:
    driver: bridge
